CLI/Interface option to request no constructors for certain structs (#155)
* CLI/Interface option to request no constructors for certain structs

Some structs have humongous apply methods which fail to compile because
the emitted UTF-8 string with method description is too large:

java.lang.IllegalArgumentException: UTF8 string too large while compiling /Users/velvetbaldmime/projects/sn-bindgen/libnotify.scala
Exception in thread "main" java.lang.IllegalArgumentException: UTF8 string too large
        at scala.tools.asm.ByteVector.putUTF8(ByteVector.java:255)
        at scala.tools.asm.SymbolTable.addConstantUtf8(SymbolTable.java:774)
        at scala.tools.asm.MethodWriter.<init>(MethodWriter.java:603)

There isn't much we can do at this point, so we just allow the user to
control the rendering of this particular method.

* Add tests for CLI argument parsing
* Don't print full help on error